### PR TITLE
Rename enum values and color names to match C# naming convention

### PR DESCRIPTION
**Pull request by danilwhale**
This could be BREAKING change for existing projects.
Examples are synced to this change
Examples:
Color.RAYWHITE -> Color.RayWhite
KeyboardKey.KEY_F3 -> KeyboardKey.F3
MouseButton.MOUSE_BUTTON_LEFT -> MouseButton.Left

### CODE REVIEW

**Comment by MrScautHD** [comment]
i like it!

**Comment by ChrisDill** [comment]
@danilwhale I think this is a good idea. Initially I matched the raylib style but over time found the api nicer when moving it closer to the C# style. It is a breaking change so the next release will be 6.0.0.

Fix the conflicts so it works with the update to raylib 5.0 and I will accept the PR.

**Comment by danilwhale** [comment]
okay, no problem

**Comment by danilwhale** [comment]
looks like i cant use github lmao
i will open another pull request because im stupid

**Comment by danilwhale** [comment]
https://github.com/ChrisDill/Raylib-cs/pull/224

**Pull request closed without merging**
