### PR TITLE
Port to Raylib-5.0.0

### PR DESCRIPTION
**Pull request by MrScautHD**
This pull request is a work in progress (WIP).
I have initiated the process by beginning the port to `Raylib-5.0.0`.

Issue: https://github.com/ChrisDill/Raylib-cs/issues/209

### CODE REVIEW

**Comment by MrScautHD** [comment]
Android got a build error has anyone a idea why?

**Comment by ChrisDill** [comment]
Seems to be a difference in how warnings are handled when comparing it to the other platform builds. Not sure why though.

**Comment by akgvn** [comment]
@MrScautHD the problem seems to be related to this: https://github.com/raysan5/raylib/issues/3491

**Comment by MrScautHD** [comment]
> @MrScautHD the problem seems to be related to this: [raysan5/raylib#3491](https://github.com/raysan5/raylib/issues/3491)
> 
> **Edit:** `CMakeLists.txt` file needs patching similar to how its done here: https://github.com/Bigfoot71/Raymob/blob/cb0bd177c8266b9e623f1cdf496e07fb251d5173/app/src/main/cpp/deps/raylib/CMakeLists.txt#L26
> 
> Another option is to use the makefile instead of cmake since that already handles the problem in raylib main branch: https://github.com/raysan5/raylib/blob/7e60227720515143712e1df9e78e7a6ecfc46169/src/Makefile#L361-L366

ah ok, sadly im very bad in msBuild so can anyone fix that for me? (Or merge it and fix it with a commit)

**Comment by CodingMadness** [comment]
Is the port still going on?

**Comment by CodingMadness** [comment]
> Yea, but idk how to fix the android build i would like if anyone could help ☺️

I will dive into this when I see time, need 2 days tho due to some work I will have to do for my job, then I will look into it with pleasure.

**Comment by MrScautHD** [comment]
> > Yea, but idk how to fix the android build i would like if anyone could help ☺️
> 
> I will dive into this when I see time, need 2 days tho due to some work I will have to do for my job, then I will look into it with pleasure.

And do you know how to fix it?

**Comment by CodingMadness** [comment]
> > > Yea, but idk how to fix the android build i would like if anyone could help ☺️
> > 
> > 
> > I will dive into this when I see time, need 2 days tho due to some work I will have to do for my job, then I will look into it with pleasure.
> 
> And do you know how to fix it?

Big sry, I was getting sick lately and it lasted like 11 days.. and had to prepare for christmas and such, so my head where no where really. 

But today I asked abit the owner of raylib and he replied this:

 
[chatlog.txt](https://github.com/ChrisDill/Raylib-cs/files/13719442/chatlog.txt)

Hope that gets you a bit of an idea of what is going wrong.

**Comment by MrScautHD** [comment]
@ChrisDill What do you think by doing a own branch for it so everyone can help to port to Raylib-5.0

**Comment by MrScautHD** [comment]
finally :D

**Comment by MrScautHD** [comment]
@ChrisDill it should be done.

**Review by ChrisDill — APPROVED** [review]

**Comment by ChrisDill** [comment]
@MrScautHD Looks good. Thanks for fixing the build issue!

**Comment by CodingMadness** [comment]
> @ChrisDill it should be done.

Was my last message somewhat useful 😅 ?

**Comment by Odex64** [comment]
You really should update the NuGet package.
Also consider switching to .NET 8 since it's LTS.

**Pull request merged**
