### PR TITLE
Update names of methods, variables, and other elements 

### PR DESCRIPTION
**Pull request by ChrisDill**
PR preparing to merge naming changes from #167.

### CODE REVIEW

**Comment by MrScautHD** [comment]
anything else, what need todo?

**Comment by ChrisDill** [comment]
@MrScautHD Changes look good. Last few checks then this will be merged.

**Comment by MrScautHD** [comment]
What about changing the name from classes to something like from Raymath to RayMath

**Comment by ChrisDill** [comment]
I think the interop class naming is fine as it is. I see Raymath as one full word like Raylib.

**Comment by MrScautHD** [comment]
well, what about the namespace?

like Raylib_cs is a bit wierd, what about just calling it Raylib?

**Comment by ChrisDill** [comment]
The namespace is called that to help make it clearer that it is a binding to raylib. Also the main interop class is already called Raylib.

**Comment by MrScautHD** [comment]
> The namespace is called that to help make it clearer that it is a binding to raylib. Also the main interop class is already called Raylib.

mhh, well it is your lib.

Anyway did you see anything else that need to be changed or fixed?

**Comment by MrScautHD** [comment]
AnsiBuffer need to be fixed to now!

**Comment by ChrisDill** [comment]
@MrScautHD Looks good. Merged!

**Comment by MrScautHD** [comment]
Amazing!

**Pull request merged**
