### PR TITLE
Native build improvements

### PR DESCRIPTION
**Pull request by chrisdill**
### Why?
- Document changes for **our own binaries of raylib** to more clearly follow the license
- Not all features of Raylib are enabled by default in the official builds
- Some features are more necessary for some projects
- We want Raylib-cs to be "Batteries included" for most common use cases. Most users shouldn't have to build their own version of Raylib, just to change some compile flags.
- Single build setup for both local and action builds

NOTE: Confirmed our current approach to distributing **our own binaries of raylib** is okay with Ray.

### CODE REVIEW

**Comment by MrScautHD** [comment]
With nuget? :)

**Comment by ChrisDill** [comment]
Not part of the nuget package. Goal is to improve/integrate Raylib-cs.Native with github actions.

**Comment by MrScautHD** [comment]
What you think about that.
grafik

**Comment by ChrisDill** [comment]
I want to stick to just the one nuget package and once you need a custom build it would be better to have full control over it in your project instead of trying to override settings in the package.

I would like to give the users control over including the prebuilt libraries which could help but I am not sure if that is possible with nuget.

**Pull request merged**
