### PR TITLE
[Feature #179] MeshExtensions

### PR DESCRIPTION
**Pull request by n77y**
Add mesh generation extensions as requested here: #179

### CODE REVIEW

**Comment by ChrisDill** [comment]
The MeshExtensions class needs to be public not internal. Once fixed this can be merged in. Thanks!

**Comment by n77y** [comment]
@ChrisDill, as far as I’m aware structs always have a default constructor. So adding a default constructor that does nothing would be redundant, unless you want to change the default behavior?

**Comment by ChrisDill** [comment]
Good point. Default behaviour is fine then as I got it mixed up with classes.

**Comment by ChrisDill** [comment]
Thanks, merged!

**Comment by MrScautHD** [comment]
Amazing work!

**Pull request merged**
