### PR TITLE
Update to raylib 5.5

### PR DESCRIPTION
**Pull request by JupiterRider**
#278 

Update:
@chrisdill @9ParsonsB  This PR is ready now.

### CODE REVIEW

**Comment by chrisdill** [comment]
@JupiterRider Thanks for the PR. Looks okay to me though ideally need a few more people to test/check for edge cases which can easily happen with bindings.

**Review by chrisdill — APPROVED** [review]

**Comment by JupiterRider** [comment]
@chrisdill Maybe you can publish a Pre-release, so people can test the new version?

**Comment by chrisdill** [comment]
@JupiterRider Tried that with the release before and not enough people tried it.

**Comment by 9ParsonsB** [comment]
after testing on all the platforms we have access to, we usually just release and wait. Making a new point release is very easy, this way we get faster & wider feedback.

**Comment by WoozChucky** [comment]
Hello there, I've tested https://github.com/JupiterRider/Raylib-cs/commit/b6ce2bdd88b75cfde64e056e8097be56d2fa6802 on my game, and have found no issues so far 👍

**Comment by JupiterRider** [comment]
@WoozChucky Thanks form testing, but b6ce2bdd88b75cfde64e056e8097be56d2fa6802 is a independent from this.
Nonetheless, I think this pull request should be merged. I don't see any reason to wait.

**Comment by WoozChucky** [comment]
Sorry I meant that I have tested your branch at that commit with was your latest at the time 👍

**Comment by Cronos87** [comment]
Is the .NET version still targeting 6.0? I'm not familiar with the .NET ecosystem. Thanks for the answer 🙏

**Comment by chrisdill** [comment]
@Cronos87 Still targeting net6.0.

@JupiterRider Would prefer a few more people test but overall it looks okay so I will merge it in.

**Comment by JupiterRider** [comment]
> @JupiterRider Would prefer a few more people test but overall it looks okay so I will merge it in.

I think once you've release the nuget package, people will use the new code and report issues (if there are any).
I'll try to keep an eye on this repository, and help if possible.

**Pull request merged**
