### PR TITLE
Fixed problem where Xbox controller wouldn't appear for `InputGamepad`.

### PR DESCRIPTION
**Pull request by WraithGlade**
I've fixed the problems associated with this file which I detailed in my issue report [here](https://github.com/ChrisDill/Raylib-cs/issues/195) (issue #195).

My version of Raylib-cs is slightly different from the bleeding edge master branch but still recent, and my project setup is slightly different too, but I think this change should still work. You should test it to check though.

I didn't use the manual method for setting up Raylib-cs. I used the automatic one using the package management system (simple command line install).

The current master branch for Raylib-cs says it has a broken build, whereas the version I'm using doesn't have that. So, this code change was tested on my version because I don't know whether I'd be able to get the currently broken (but most recent) master branch of Raylib-cs working.

The diff comparison looks messed up but the file should work. I don't have more time to work on this today but wanted to send it in. Sorry about the messed up diff.

Maybe the line endings got changed? That's my best guess on why it did that.

### CODE REVIEW

**Comment by 9ParsonsB** [comment]
Thanks for sending this in! 

Definitely need to fix the diff, it looks like you need to rebase your changes as your PR currently uses block-scoped namespace, when we recently changed to file-scoped namespace.

You also pointed out that the names for gamepads is incorrect, and I think we should have a more holistic solution for this (and not use `const`, as to avoid const-interning), as gamepads, as you point out, should have first-class supported.

@ChrisDill we might need to acquire some hardware, maybe make a table of all the different controllers we support, who tests it, device names, platforms, etc.

Master branch build is failing the publish task, when building the Android project as support for Android is still in-progress.

**Comment by WraithGlade** [comment]
Thanks for the information.

I was (and still am) wary of trying to build the broken master branch. Wouldn't it be better to always ensure the head of master branch is always a valid non-broken build and to do big changes in a separate branch until you are actually ready to merge?

Allowing broken code exist in the main branch is likely to confuse a lot of people and reduce people's willingness to attempt contributions.

I'm not sure why const-interning would be a problem. My understanding was that interning strings like these makes them much faster to compare with `==` since a character by character comparison isn't necessary if the strings are interned as constants and can just have their references compared instead. Perhaps the deeper nuances of C#'s interning works differently than in other languages though. In either case though, having the condition check each possibility in runtime instead of conditionally compiling which controller ID string is used seems safer, since for all we know it the OS or drivers or devices could change their IDs and its not like we lose anything real by checking all the name possibilities. So, I don't really understand the problem with that, if one exists at all.

I'm going to try to fix my commit. It has been years since the last time I had to rebase since usually I keep things clean, so it may take a bit while I figure out how to do this again. 

I avoided using master branch because it is seldom ever a good idea to build off of known-to-be-broken branches, but I guess I'll try overwriting the file anyway and try to build it from the working stable version of Raylib-cs.

**Comment by WraithGlade** [comment]
I edited my commit via a 2nd commit that fixed the namespace indentation that messed up the diff before.

This way the history of this discussion will still be visible in the commits.

Alternatively, should I rebase it to create a "clean" history with just one commit?

What are your preferences?

**Comment by ChrisDill** [comment]
@WraithGlade No preference on commits in pull requests as long as it is clear what changes are being made. Using squash and merge so it will end up as 1 commit when it gets merged.

I agree that the master branch should ideally always be valid. Currently failing because of work on experimental android support. Disabled this part of the workflow for now so if you add the latest change this branch should build okay. I will keep this in mind for future changes.

**Comment by WraithGlade** [comment]
Ok, good to know and thanks for the info and for responding to my suggestions etc.

Have a great day/night!

**Comment by ChrisDill** [comment]
Thanks, merged!

**Pull request merged**
