### PR TITLE
Implement Managed Code Friendly version of CheckCollisionPointPoly

### PR DESCRIPTION
**Pull request by AlexanderBaggett**

### CODE REVIEW

**Comment by chrisdill** [comment]
Looks okay though is there a reason this uses `Unsafe.AsPointer` instead of `fixed` like the other util methods?

**Comment by AlexanderBaggett** [comment]
Fair point, I'll update that in my PR.

**Comment by chrisdill** [comment]
Thanks. Does it also need MemoryMarshal.GetArrayDataReference?

**Comment by AlexanderBaggett** [comment]
This is the obvious way to do it (at least for me).

I've seen an AI spit out code that suggests a different way to do it.
But usually AI's are not great at C# interop code.

I'll check that alternate way tonight and let you know if it works.

**Comment by AlexanderBaggett** [comment]
> Thanks. Does it also need MemoryMarshal.GetArrayDataReference?

To answer definitively: No

It seems like there is a simpler more straightforward approach.  I went ahead and updated my code to go with that approach instead.

**Comment by chrisdill** [comment]
Please update it to `fixed (Vector2* pointsPtr = &points)`.

**Comment by AlexanderBaggett** [comment]
> Please update it to `fixed (Vector2* p = points)` to match other usages such as DrawTriangleStrip.

done

**Comment by chrisdill** [comment]
Thanks, merged!

**Pull request merged**
